### ISSUE TITLE
Why is the access level for the parsedLine property of the Parser set to fileprivate?

### ISSUE THREAD

**Issue by livingstonef** [WholeCheese/CSV#1]
If the CSVParserDelegate is in another file, there is probably no other way to access the parsedLine in the delegate as the only parameter passed is the parser itself. 

Why is this?

**Comment by WholeCheese** [comment]
I am not quite sure what you are looking for. The delegate function parserDidReadLine receives each line of the csv file as an array of parsed string values. If you do not want a csv parser but only want each line of a text file then just use the text file reader.  Also note that a "line" in a csv file can span more than one line in a text file if a field contains quoted newline characters. Does this answer your question?

-Allan

**Comment by livingstonef** [comment]
Oh great. awesome did not see that the parserDidReadLine method received the parsed line. Just what i needed. 

Thanks

**Comment by WholeCheese** [comment]
Glad that was it!  I saw other CSV implementations on GIT that utilized the Swift closure method of doing things but I wanted to do kind of an XML Sax parser thing with delegate methods.  If you know of a good validation of one over the other please let me know!
